#!/usr/bin/env python
import sys

words = set()
path = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/dict/words"
for line in open(path, "r"):
  words.add(line.strip())

for line in sys.stdin.xreadlines():
  for word in line.strip().split():
    if word.lower() in words:
      print word,
    else:
      print "<%s>" % word,
  print

